
[common]
	#The amount of rows in the shulkerpack inventory. Each row is nine slots of storage.
	#Range: 1 ~ 6
	shulkerpackInventorySize = 3
	#The amount of rows in the rucksack inventory. Each row is nine slots of storage.
	#Range: 1 ~ 6
	rucksackInventorySize = 2
	#The amount of rows in the nethersack inventory. Each row is nine slots of storage.
	#Range: 1 ~ 6
	nethersackInventorySize = 5

