
#Mob Configuration
[mob_configuration]
	#Enable Iceologers to spawn in snowy or icy biomes. 
	#If you have an alternative way to spawn them, disable this feature. [true / false]
	enableIceologerSpawns = true
	#Spawn weight of iceologers in snowy or icy biomes.
	#Range: 0 ~ 1024
	iceologerSpawnWeight = 5
	#Minimum spawn group size of iceologers in snowy or icy biomes.
	#Range: 0 ~ 1024
	iceolgoerMinSpawnGroupSize = 1
	#Enable Iceologers to spawn in raids, in the same waves as the Evoker. 
	#If you don't want them to spawn in raids, disable this feature. [true / false]
	enableIceolgersInRaids = true
	#Maximum spawn group size of iceologers in snowy or icy biomes.
	#Range: 0 ~ 1024
	iceologerMaxSpawnGroupSize = 1

