
#Nether Extension client configuration
[client]

	[client.entities]
		#If Piglin outfits have variation; Default: true
		"Variant Piglins" = true
		#If Hoglins can be renamed to have a business suit; Default: true
		"Business Hoglin" = true

	[client.potions]
		#If the potion effects should no longer shift the inventory when active; Default: true
		"Remove potion shift" = true
		#If the potion glint should be removed; Default: true
		"Remove potion glint" = true

