
#Nether Extension common configuration
[common]

	[common.potions]
		#The max stack size of potions; Default: 16
		"Potion stack size" = 16
		#If potions can be stacked; Default: true
		"Stackable potions" = false

