
["Rings of Ascension"]
	#The amount of hearts that Max Health's ring gives you.
	#Range: 0 ~ 400
	ringHealthHearts = 20
	#The cooldown in seconds of the Ring of Undying
	#Range: > 0
	ringUndyingCooldown = 600

["Enable/Disable Rings"]
	ringWaterWalking = true
	ringMagnetism = true
	ringSponge = true
	ringNightVision = true
	ringRegeneration = true
	ringPoisonResistance = true
	ringStrength = true
	ringGrowth = true
	ringInvisibility = true
	ringWaterBreathing = true
	ringWither = true
	ringDolphin = true
	ringKnockbackResistance = true
	ringHungerless = true
	ringFireResistance = true
	ringExperience = true
	ringMining = true
	ringHealth = true
	ringSlowResistance = true
	ringJumpBoost = true
	ringLuck = true
	ringSpeed = true
	ringUndying = true
	ringSlowFalling = true
	ringFlight = true

["Rings Amplifier"]

	#Sets the amplifier of the effect given by the ring. Example:
	#0 = Fire Resistance I
	#1 = Fire Resistance II
	["Rings Amplifier".Amplifiers]
		#Range: 0 ~ 255
		ringAmplifierSlowFalling = 0
		#Range: 0 ~ 255
		ringAmplifierJumpBoost = 0
		#Range: 0 ~ 255
		ringAmplifierDolphin = 0
		#Range: 0 ~ 255
		ringAmplifierInvisibility = 0
		#Range: 0 ~ 255
		ringAmplifierWaterBreathing = 1
		#Range: 0 ~ 255
		ringAmplifierLuck = 1
		#Range: 0 ~ 255
		ringAmplifierRegeneration = 0
		#Range: 0 ~ 255
		ringAmplifierFireResistance = 1
		#Range: 0 ~ 255
		ringAmplifierStrength = 0
		#Range: 0 ~ 255
		ringAmplifierMining = 1
		#Range: 0 ~ 255
		ringAmplifierSpeed = 0
		#Range: 0 ~ 255
		ringAmplifierNightVision = 0

["Rings Tier"]

	#Sets the Tier of the rings. Higher tier rings are more difficult to find.
	#0 = Common
	#1 = Rare
	#2 = Epic
	#3 = Legendary
	#4 = Mythic
	["Rings Tier".Tiers]
		#Range: 0 ~ 4
		ringTierWaterBreathing = 0
		#Range: 0 ~ 4
		ringTierKnockbackResistance = 0
		#Range: 0 ~ 4
		ringTierNightVision = 0
		#Range: 0 ~ 4
		ringTierPoisonResistance = 2
		#Range: 0 ~ 4
		ringTierSlowFalling = 0
		#Range: 0 ~ 4
		ringTierMagnetism = 2
		#Range: 0 ~ 4
		ringTierSponge = 1
		#Range: 0 ~ 4
		ringTierSpeed = 1
		#Range: 0 ~ 4
		ringTierWither = 1
		#Range: 0 ~ 4
		ringTierHealth = 3
		#Range: 0 ~ 4
		ringTierLuck = 3
		#Range: 0 ~ 4
		ringTierRegeneration = 3
		#Range: 0 ~ 4
		ringTierDolphin = 1
		#Range: 0 ~ 4
		ringTierWaterWalking = 0
		#Range: 0 ~ 4
		ringTierInvisibility = 1
		#Range: 0 ~ 4
		ringTierGrowth = 2
		#Range: 0 ~ 4
		ringTierMining = 2
		#Range: 0 ~ 4
		ringTierUndying = 4
		#Range: 0 ~ 4
		ringTierFireResistance = 0
		#Range: 0 ~ 4
		ringTierStrength = 2
		#Range: 0 ~ 4
		ringTierHungerless = 3
		#Range: 0 ~ 4
		ringTierJumpBoost = 0
		#Range: 0 ~ 4
		ringTierSlowResistance = 1
		#Range: 0 ~ 4
		ringTierFlight = 4
		#Range: 0 ~ 4
		ringTierExperience = 0

["Rings Loot"]
	#The maximum number of rings that can be found inside a single chest.
	ringMaxLoot = 2
	#The minimum number of rings that can be found inside a single chest. Values below 0 decrease the chance of the rings appearing.
	ringMinLoot = -2

["Rings Locations"]
	ringLocationPoisonResistance = "minecraft:chests/jungle_temple;minecraft:chests/end_city_treasure;minecraft:chests/shipwreck_treasure;minecraft:chests/bastion_treasure;minecraft:chests/bastion_bridge"
	ringLocationKnockbackResistance = "minecraft:chests/end_city_treasure;minecraft:chests/bastion_bridge;minecraft:chests/nether_bridge"
	ringLocationJumpBoost = "minecraft:chests/end_city_treasure;minecraft:chests/igloo_chest;minecraft:chests/desert_pyramid"
	ringLocationDolphin = "minecraft:chests/underwater_ruin_big;minecraft:chests/underwater_run_small;minecraft:chests/buried_treasure"
	ringLocationGrowth = "minecraft:chests/jungle_temple"
	ringLocationFlight = "minecraft:chests/end_city_treasure"
	ringLocationWaterWalking = "minecraft:chests/underwater_ruin_big;minecraft:chests/underwater_run_small;minecraft:chests/buried_treasure"
	ringLocationLuck = "minecraft:chests/simple_dungeon;minecraft:chests/jungle_temple"
	ringLocationUndying = "minecraft:chests/woodland_mansion"
	ringLocationRegeneration = "minecraft:chests/stronghold_corridor;minecraft:chests/stronghold_library"
	ringLocationMining = "minecraft:chests/simple_dungeon;minecraft:chests/abandoned_mineshaft"
	ringLocationSpeed = "minecraft:chests/spawn_bonus_chest;minecraft:chests/simple_dungeon;minecraft:chests/buried_treasure"
	ringLocationHealth = "minecraft:chests/end_city_treasure;minecraft:chests/bastion_treasure;minecraft:chests/stronghold_library"
	ringLocationHungerless = "minecraft:chests/village/village_butcher;minecraft:chests/end_city_treasure;minecraft:chests/woodland_mansion"
	ringLocationSlowResistance = "minecraft:chests/end_city_treasure;minecraft:chests/shipwreck_treasure;minecraft:chests/bastion_treasure;minecraft:chests/bastion_bridge"
	ringLocationFireResistance = "minecraft:chests/nether_bridge;minecraft:chests/ruined_portal;minecraft:chests/bastion_treasure"
	ringLocationStrength = "minecraft:chests/stronghold_library;minecraft:chests/stronghold_corridor;minecraft:chests/stronghold_crossing;minecraft:chests/bastion_treasure;minecraft:chests/bastion_bridge;minecraft:chests/pillager_outpost"
	ringLocationNightVision = "minecraft:chests/spawn_bonus_chest;minecraft:chests/simple_dungeon;minecraft:chests/abandoned_mineshaft"
	ringLocationWaterBreathing = "minecraft:chests/spawn_bonus_chest;minecraft:chests/underwater_ruin_big;minecraft:chests/underwater_run_small;minecraft:chests/buried_treasure"
	ringLocationExperience = "minecraft:chests/spawn_bonus_chest;minecraft:chests/simple_dungeon;minecraft:chests/buried_treasure;minecraft:chests/ruined_portal"
	ringLocationWither = "minecraft:chests/bastion_treasure"
	ringLocationSlowFalling = "minecraft:chests/simple_dungeon;minecraft:chests/buried_treasure;minecraft:chests/end_city_treasure"
	ringLocationInvisibility = "minecraft:chests/abandoned_mineshaft;minecraft:chests/buried_treasure"
	ringLocationMagnetism = "minecraft:chests/spawn_bonus_chest;minecraft:chests/simple_dungeon;minecraft:chests/buried_treasure;minecraft:chests/ruined_portal"
	ringLocationSponge = "minecraft:chests/underwater_ruin_big;minecraft:chests/underwater_run_small"

