
["Drop rates"]
	#Drop chance for monster eggs. Value in percentage (%) ranging from 0 - 100. Default is 4.
	#Range: 0.0 ~ 100.0
	monster_egg_drop_chance = 1.0

["Monster Spawner"]
	#Disable/Eanble the Range option.
	disable_range = false
	#Disable/Eanble the ability to right click the spawner for getting the monster egg.
	disable_egg_removal_from_spawner = false
	#Disable/Eanble the Speed option.
	disable_speed = false
	#Disable/Eanble the ability to silk touch a spawner.
	disable_silk_touch = false
	#Disable/Eanble the spawner config screen.
	disable_spawner_config = false
	#Disable/Eanble the Count option.
	disable_count = false

