
[General]
	#If Giant Spawn should be enabled. Allows the giant to spawn naturally and other tweaks.
	enableGiantSpawn = false
	#If Kelp Fertilizer should be enabled. Kelp seaweed has a cell structure that filters sea water for rich nutrients. It can now act as a fertilizer like bone meal.
	enableKelpFertilizer = false
	#If Villager Death Messages should be enabled. Broadcasts an informational death message whenever a villager passes away.
	enableVillagerDeathMessages = false
	#If Superflat World No Slimes should be enabled. Removes those pesky slimes when you're trying to be creative in a superflat world.
	enableSuperflatWorldNoSlimes = true
	#If ALL mods should be enabled. Ignores the other settings when enabled.
	_enableALL = false
	#If Fixed Anvil Repair Cost should be enabled. Allows setting the level and material cost of repairing an item on an anvil to always be the same configurable amount and also allows setting how much percent is repaired.
	enableFixedAnvilRepairCost = true
	#If Underwater Enchanting should be enabled. Allows the use of the enchantment table under water with maximum levels via bookshelves.
	enableUnderwaterEnchanting = true
	#If Name Tag Tweaks should be enabled. Adds name tag crafting recipe, /nametag command, and named entities drop their name tag on death.
	enableNameTagTweaks = true
	#If Inventory Totem should be enabled. Makes the totem of undying effect work when existing in the player's inventory.
	enableInventoryTotem = true
	#If Fall Through Slime should be enabled. Slime blocks no longer support your weight when standing still, and you'll slowly fall through.
	enableFallThroughSlime = false
	#If Easy Elytra Takeoff should be enabled. Allows easy taking off by elytra with a firework from the ground without that awkward jump.
	enableEasyElytraTakeoff = true
	#If Extract Poison should be enabled. Allows the extraction of poison from cave spiders, pufferfish and bees with an empty bottle.
	enableExtractPoison = false
	#If Passive Endermen should be enabled. Configurably prevent an enderman from picking up blocks, griefing and attacking players.
	enablePassiveEndermen = false
	#If Mineral Chance should be enabled. Adds a chance to find a random mineral inside a stone block when mining.
	enableMineralChance = false
	#If Double Doors should be enabled. Adds the ability for identical double doors, trapdoors and fence gates to be opened simultaneously via click or pressure plates and buttons.
	enableDoubleDoors = false
	#If Grass Seeds should be enabled. A minimalistic mod which allows players to use normal seeds to transform dirt to grass.
	enableGrassSeeds = true
	#If Shulker Drops Two should be enabled. A minimalistic configurable mod that allows shulkers to drop two or more shells and ignore their default drop chance.
	enableShulkerDropsTwo = true
	#If Stack Refill should be enabled. Automatically refills the item in the hand of the player when using the final item if possible.
	enableStackRefill = false
	#If Campfire Spawn and Tweaks should be enabled. Allows player to set spawn points inside a campfire, gives fire resistance on respawn and does some other tweaks.
	enableCampfireSpawnandTweaks = false
	#If Mooshroom Tweaks should be enabled. A minimalistic mod that tweaks the spawning behaviour of mooshrooms, allowing both red and brown to spawn naturally.
	enableMooshroomTweaks = false
	#If Snowballs Freeze Mobs should be enabled. Hitting mobs with a snowball will result in them being frozen for a configurable amount of time.
	enableSnowballsFreezeMobs = false
	#If Breedable Killer Rabbit should be enabled. A minimalistic configurable mod which makes the killer rabbit tamable and available by breeding.
	enableBreedableKillerRabbit = false
	#If Infinite Trading should be enabled. Prevents villager trades from locking up, making them be always available.
	enableInfiniteTrading = true
	#If Dragon Drops Elytra should be enabled. A minimalistic mod that makes the Ender Dragon drop an elytra on death.
	enableDragonDropsElytra = true
	#If Crying Ghasts should be enabled. Ghasts drop their tears periodically when a player is close, giving the ability to farm them sustainably.
	enableCryingGhasts = false
	#If Milk All The Mobs should be enabled. Allows sheep, llamas, pigs, donkeys, horses and mules to produce a bucket of milk.
	enableMilkAllTheMobs = false
	#If End Portal Recipe should be enabled. Makes the end portal craftable and available in survival plus other tweaks.
	enableEndPortalRecipe = false
	#If Edibles should be enabled. Makes lots of ingredients edible, after which the player receives a short status effect.
	enableEdibles = false
	#If Starter Kit should be enabled. Gives players who join the world for the first time configurable starter gear.
	enableStarterKit = false
	#If More Zombie Villagers should be enabled. Allows modifying the default chance a zombie spawn is of the villager variant.
	enableMoreZombieVillagers = false
	#If Villager Names should be enabled. A minimalistic mod which gives all unnamed villagers a (pre-)defined name.
	enableVillagerNames = true
	#If Extended Bone Meal should be enabled. Extends bone meal behaviour. Instant grow with sneak, grow netherwart and other tweaks.
	enableExtendedBoneMeal = true
	#If Just Mob Heads should be enabled. A minimalistic mod that adds a configurable chance for mobs to drop their respective heads on death.
	enableJustMobHeads = true
	#If Cycle Paintings should be enabled. Easily cycle through placed paintings by right-clicking them with another painting.
	enableCyclePaintings = true
	#If Bottle Your Xp should be enabled. A minimalistic configurable mod that allows the creation of experience bottles from your own gathered xp.
	enableBottleYourXp = false
	#If All Loot Drops should be enabled. A minimalistic mod that has entities always drop all their possible loot in a configurable amount.
	enableAllLootDrops = false
	#If Pet Names should be enabled. Gives tamable baby animals a pre-defined name. For Wolves, Cats, Horses, Donkeys, Mules and Llamas.
	enablePetNames = false
	#If Random Bone Meal Flowers should be enabled. Randomizes the flowers spawned by bone meal, allowing all (modded) types to spawn everywhere.
	enableRandomBoneMealFlowers = true
	#If Nether Portal Spread should be enabled. Nether portals spread (custom) nether blocks to the overworld around the portal in a configurable radius.
	enableNetherPortalSpread = false
	#If Wool Tweaks should be enabled. Dye beds, wool blocks and beds with a right-click in the world. Adds wool to string recipe for all wool blocks and allows players to dye any colour wool block with any dye.
	enableWoolTweaks = true
	#If Spiders Produce Webs should be enabled. Spiders and cave spiders can periodically produce a web when a player is close.
	enableSpidersProduceWebs = false
	#If Just Player Heads should be enabled. A minimalistic mod that adds a configurable chance for players to drop their respective heads on death and via a command. All heads are generated with texture-data.
	enableJustPlayerHeads = true
	#If Scaffolding Drops Nearby should be enabled. When breaking a scaffolding block, all chained blocks will drop at the first block's position.
	enableScaffoldingDropsNearby = true
	#If Recipe Commands should be enabled. Adds the ability to receive the pattern and ingredients of any recipe via chat by a command.
	enableRecipeCommands = false
	#If Enchanting Commands should be enabled. A minimalistic mod which allows for easy creation of enchanted items via commands with levels above the default limit. Usage: /ec
	enableEnchantingCommands = true
	#If Eroding Stone Entities should be enabled. When stone-type entities are left in flowing water for some time they turn into sand.
	enableErodingStoneEntities = false
	#If GUI Compass should be enabled. Shows the direction and coordinates in the GUI with a compass in the inventory.
	enableGUICompass = false
	#If Zombie Villagers From Spawner should be enabled. Puts back the ability for zombie spawners to spawn the villager variant, removed in 1.11.
	enableZombieVillagersFromSpawner = true
	#If Despawning Eggs Hatch should be enabled. Allows chicken eggs on a hay block to hatch into a chick baby just before they despawn.
	enableDespawningEggsHatch = false
	#If GUI Followers should be enabled. [Client] Shows a list in the GUI/HUD with all tamed non-sitting followers around the player.
	enableGUIFollowers = false
	#If Transcending Trident should be enabled. Improves the vanilla trident. Hold a water bucket to use riptide, which is more powerful.
	enableTranscendingTrident = false
	#If Random Village Names should be enabled. Gives all villages a random name from a preset list. Uses the Areas mod to display the name in the GUI.
	enableRandomVillageNames = true
	#If Softer Hay Bales should be enabled. Makes hay bales negate fall damage entirely, Assassin's Creed style.
	enableSofterHayBales = true
	#If Stray Spawn should be enabled. Allows a chance for strays to spawn naturally everywhere instead of a skeleton.
	enableStraySpawn = false
	#If Random Sheep Colours should be enabled. Gives new sheep spawns a random wool colour based on a configurable list.
	enableRandomSheepColours = false
	#If Village Spawn Point should be enabled. Sets the spawn point of a new world to always be in the center of a village.
	enableVillageSpawnPoint = false
	#If Advancement Screenshot should be enabled. A client-side mod which takes a screenshot every time a player achieves an advancement.
	enableAdvancementScreenshot = true
	#If Hide Hands should be enabled. Hide your offhand and/or mainhand, always or while holding specific items.
	enableHideHands = false
	#If Village Bell Recipe should be enabled. Adds a recipe for the village bell item.
	enableVillageBellRecipe = false
	#If Conduits Prevent Drowned should be enabled. Disables drowned zombie spawns around the player when the conduit effect is active.
	enableConduitsPreventDrowned = true
	#If Replanting Crops should be enabled. Automatically replants/replaces/reseeds crops harvested with seeds from drops, negated by holding the sneak button.
	enableReplantingCrops = false
	#If Move Minecarts should be enabled. Allows players to easily pick up and move minecarts without breaking them by holding right click.
	enableMoveMinecarts = true
	#If Hand Over Your Items should be enabled. Adds to ability to give other players items without dropping them on the floor.
	enableHandOverYourItems = true
	#If Ice Prevents Crop Growth should be enabled. Crops growing on tilled soil with an ice block underneath will never grow to the next stage, for design purposes.
	enableIcePreventsCropGrowth = true
	#If Zombie Proof Doors should be enabled. Prevents zombies from targeting and breaking down doors.
	enableZombieProofDoors = false
	#If Quick Paths should be enabled. Create long paths instantly by setting a start and end point.
	enableQuickPaths = true
	#If Automatic Doors should be enabled. Automatically opens doors in front of the player and closes them with a configurable delay.
	enableAutomaticDoors = false
	#If Death Backup should be enabled. Creates a backup of an inventory right before a player death, which can be loaded via a command.
	enableDeathBackup = true
	#If Tree Harvester should be enabled. Harvest trees instantly by chopping down the bottom block with fast leaf decay and sapling replacement.
	enableTreeHarvester = false
	#If Random Shulker Colours should be enabled. Gives new shulker spawns a random shell colour based on a configurable list.
	enableRandomShulkerColours = false
	#If Creative Block Replacer should be enabled. Allows easy switching in between placing and replacing blocks in creative mode.
	enableCreativeBlockReplacer = false
	#If Paper Books should be enabled. Allows the creation of books with 9 paper.
	enablePaperBooks = false
	#If Mooshroom Spawn should be enabled. Adds a chance for mooshrooms to spawn naturally everywhere in place of a cow.
	enableMooshroomSpawn = false
	#If Better Spawner Control should be enabled. A drag-and-drop mod which disables mob spawners whenever they are surrounded by 5 torches.
	enableBetterSpawnerControl = true
	#If Recast should be enabled. Automatically re-casts the fishing rod for a player when they catch an item.
	enableRecast = false
	#If Better Conduit Placement should be enabled. Place conduits in front of you, place blocks by clicking the conduit and other tweaks.
	enableBetterConduitPlacement = true
	#If Always a Wither Skull should be enabled. A drag-and-drop mod that makes wither skeletons always drop their skull on death.
	enableAlwaysaWitherSkull = false
	#If Bigger Sponge Absorption Radius should be enabled. Each extra sponge block placed next to another increases the water absorption radius.
	enableBiggerSpongeAbsorptionRadius = true
	#If GUI Clock should be enabled. Shows the time and days played in the GUI on the screen with a clock in the inventory.
	enableGUIClock = false
	#If TNT Breaks Bedrock should be enabled. Allows TNT to break bedrock. Now you've finally got easy access to the nether roof.
	enableTNTBreaksBedrock = false
	#If Passive Shield should be enabled. The shield is hidden in the offhand until right-clicked, and shields passively negate damage when held but not in use.
	enablePassiveShield = false
	#If Fire Spread Tweaks should be enabled. Disables the default firespread, but does make fire go out on its own after a configurable delay.
	enableFireSpreadTweaks = false
	#If Skeleton Horse Spawn should be enabled. Allows the skeleton horse to spawn naturally with a skeleton riding it and other tweaks.
	enableSkeletonHorseSpawn = false
	#If Rain Be Gone Ritual should be enabled. Adds the ability to stop the rain with a multi-block structure ritual.
	enableRainBeGoneRitual = false
	#If Zombie Horse Spawn should be enabled. Allows the zombie horse to spawn with a zombie riding it and other tweaks.
	enableZombieHorseSpawn = false
	#If First Join Message should be enabled. Sends players who join a world for the first time a configurable message.
	enableFirstJoinMessage = false
	#If Better Beacon Placement should be enabled. Easily place beacon bases by right-clicking the beacon with a mineral block plus other tweaks.
	enableBetterBeaconPlacement = true
	#If Omega Mute should be enabled. [Client] The last mod you'll ever need for culling and silencing Minecraft sounds while in-game or via a file.
	enableOmegaMute = true
	#If Smaller Nether Portals should be enabled. Allows the creation of smaller nether portals, specifically 1x2, 1x3 and 2x2.
	enableSmallerNetherPortals = true
	#If Move Boats should be enabled. Allows players to easily move boats without breaking them by holding right click.
	enableMoveBoats = true
	#If No Hostiles Around Campfire should be enabled. Prevents hostile mob spawns around the campfire in a configurable radius.
	enableNoHostilesAroundCampfire = false
	#If Sleep Sooner should be enabled. A minimalistic mod that adds a configurable functionality to be able to sleep a little sooner.
	enableSleepSooner = false
	#If Nutritious Milk should be enabled. Adds a nutritious value to milk, filling up the food bar and saturation when consumed.
	enableNutritiousMilk = false
	#If Grindstone Sharper Tools should be enabled. The grindstone can temporarily increase the damage of tools used on it.
	enableGrindstoneSharperTools = false
	#If Areas should be enabled. Create custom named areas/towns with a radius using signs, which sends join and leave messages.
	enableAreas = true
	#If Fish On The Line should be enabled. Rings the bell held in your offhand when you are fishing and something's on the line.
	enableFishOnTheLine = false
	#If Respawning Shulkers should be enabled. Shulkers will respawn on their death location after a configurable delay to make them more sustainable.
	enableRespawningShulkers = true
	#If Naturally Charged Creepers should be enabled. A minimalistic mod that allows creepers to spawn charged, both naturally and from a spawn egg.
	enableNaturallyChargedCreepers = false
	#If Dismount Entity should be enabled. Allows players to dismount/remove/exit entities/mobs from mounted entities.
	enableDismountEntity = true
	#If Weaker Spiderwebs should be enabled. Breaks spider webs/cobwebs with a configurable delay when walking through.
	enableWeakerSpiderwebs = false
	#If Healing Campfire should be enabled. A minimalistic mod which creates an area around the campfire where players and passive mobs receive the regeneration effect in a configurable radius.
	enableHealingCampfire = false
	#If Husk Spawn should be enabled. Adds a chance for husks to spawn naturally everywhere instead of a zombie.
	enableHuskSpawn = false
	#If Configurable Despawn Timer should be enabled. Allows items to remain on the ground longer or shorter than the default lifespan.
	enableConfigurableDespawnTimer = false
	#If Extended Creative Inventory should be enabled. Adds all items which by default aren't in the creative inventory to a custom Extended tab.
	enableExtendedCreativeInventory = false
	#If Realistic Bees should be enabled. Makes bees more realistic without adding new objects. Bees have a chance to lose their stinger when stinging a player or entity, and will die after doing so. Stingers can be stuck in players and will need shears to be taken out to prevent further poisoning.
	enableRealisticBees = false

