
#Dynamic changes in the world
[world]
	#Want seeds to auto-plant themselves when broken?
	selfPlanting = false
	#How long a plant should take to despawn (and attempt to plant) Default Minecraft is 6000.
	#Range: > 0
	despawnTime = 1000
	#Percentage chance to plant
	#Range: 0 ~ 100
	chanceToPlant = 100
	#Is realistic predator/prey relationships activated?
	realisticRelationship = true

