
[General]
	#The amount of damage the user takes times half a heart when creating an experience bottle.
	#Range: 1 ~ 20
	halfHeartDamageAmount = 1
	#The amount of raw xp it takes to produce an experience bottle. Be careful when setting this too low, as it may enable xp duplication.
	#Range: 0 ~ 100
	rawXpConsumedOnCreation = 10
	#If enabled, damages the user whenever they create an experience bottle.
	damageOnCreation = true

