
[General]
	#How much the item is repaired per action. By default 33.33%, so 3 of 'repairCostMaterialAmount' fully repairs any item.
	#Range: 0.0 ~ 1.0
	percentRepairedPerAction = 0.3333
	#The amount of material it costs to repair an item on an anvil. A value of 0 keeps vanilla behaviour.
	#Range: 0 ~ 64
	repairCostMaterialAmount = 1
	#The amount of level it costs to repair an item on an anvil. A value of 0 keeps vanilla behaviour.
	#Range: 0 ~ 100
	repairCostLevelAmount = 3

