
[General]
	#The giant movement speed modifier relative to the base zombie movement speed.
	#Range: 0.0 ~ 20.0
	giantMovementSpeedModifier = 1.0
	#The chance a zombie that has spawned on the surface is a giant.
	#Range: 0.0 ~ 1.0
	chanceSurfaceZombieIsGiant = 0.05
	#The giant attack damage modifier relative to the base zombie attack damage.
	#Range: 0.0 ~ 20.0
	giantAttackDamageModifier = 2.0
	#If enabled, a giant will only spawn on the surface.
	onlySpawnGiantOnSurface = true
	#If enabled, burns giants when daylight shines upon them.
	shouldBurnGiantsInDaylight = true

