
[General]
	#Sends the sharpened tool user a message at 75%, 50%, 25%, 10%.
	sendUsesLeftInChat = true
	#The damage modifier of sharpened tools.
	#Range: 0.0 ~ 100.0
	sharpenedDamageModifier = 1.5
	#The prefix of the sharpened uses left in the tool name.
	nameUsesPrefix = "(Sharpened uses: "
	#Shows the uses left in the name of the item.
	showUsesLeftInItemName = true
	#The amount of sharper uses a tool has after using it on the grindstone.
	#Range: 1 ~ 5000
	usesAfterGrinding = 32
	#The suffix of the sharpened uses left in the tool name.
	nameUsesSuffix = ")"

