
[General]
	#Places the follower list in the middle.
	followerListPositionIsCenter = false
	#The vertical offset (y coord) for the follower list. This determines how far down the list should be on the screen. Can be changed to prevent GUIs from overlapping.
	#Range: 0 ~ 3000
	followerListHeightOffset = 20
	#If enabled, shows the follower's distance in blocks to the player in the GUI list.
	showFollowerDistance = true
	#The red RGB value for the clock text.
	#Range: 0 ~ 255
	RGB_R = 255
	#The format of the health string in the GUI. <health> will be replaced by the percentage of total health.
	followerHealthFormat = ": <health>%"
	#The format of the distance string in the GUI. <distance> will be replaced by distance in blocks.
	followerDistanceFormat = " (<distance> blocks)"
	#Places the follower list on the left.
	followerListPositionIsLeft = true
	#The green RGB value for the clock text.
	#Range: 0 ~ 255
	RGB_G = 255
	#The header text above the follower list.
	followerListHeaderFormat = "Followers:"
	#The blue RGB value for the clock text.
	#Range: 0 ~ 255
	RGB_B = 255
	#If enabled, shows the follower's health in the GUI list.
	showFollowerHealth = true
	#The distance in blocks around the player where the mod checks for tamed, non-sitting followers to add to the list. A value of -1 disables this feature.
	#Range: -1 ~ 300
	distanceToCheckForFollowersAround = 50
	#The time in seconds in between checking for tamed, non-sitting followers around the player.
	#Range: 0 ~ 3600
	timeBetweenChecksInSeconds = 2
	#Places the follower list on the right.
	followerListPositionIsRight = false

