
[General]
	#If enabled, players will receive a message when they give an item.
	sendItemGivenMessage = true
	#If enabled, players will only be able to give items when they are crouching/sneaking.
	mustCrouchToGiveItem = true
	#If enabled, players will receive a message when they have been given an item.
	sendItemReceivedMessage = true

