
[General]
	#If enabled, always hides the main hand. If disabled, hides the main hand when holding the items defined in hideMainHandWithItems.
	alwaysHideMainHand = false
	#The items which when held will hide the main hand if alwaysHideMainHand is disabled.
	hideMainHandWithItems = ""
	#If enabled, always hides the offhand. If disabled, hides the offhand when holding the items defined in hideOffhandWithItems.
	alwaysHideOffhand = false
	#The items which when held will hide the offhand if alwaysHideOffhand is disabled.
	hideOffhandWithItems = "minecraft:totem_of_undying,minecraft:torch"

