
[General]
	#The chance a mineral is dropped when a stone block is broken. By default 1/50. Overworld stone blocks are stone, andesite, granite and diorite. Nether stone blocks are netherrack.
	#Range: 0.0 ~ 1.0
	extraMineralChanceOnStoneBreak = 0.02
	#If enabled, minerals won't be dropped if the player is a fake. For example when a mod breaks a block as a simulated player.
	ignoreFakePlayers = true
	#If enabled, sends a message when a mineral is found to the player who broke the stone block.
	sendMessageOnMineralFind = true
	#If enabled, mining overworld stone blocks in the overworld has a chance to drop an overworld mineral. These consist of diamonds, gold nuggets, iron nuggets, lapis lazuli, redstone and emeralds.
	enableOverworldMinerals = true
	#If enabled, mining nether stone blocks in the nether has a chance to drop a nether mineral. These consist of quartz and gold nuggets.
	enableNetherMinerals = true
	#The message sent to the player who found a hidden mineral when 'sendMessageOnMineralFind' is enabled.
	foundMineralMessage = "You've found a mineral hidden in the block!"

