
[General]
	#If enabled, burns all hostile mobs around the campfire within the radius whenever a player places a campfire.
	burnHostilesAroundWhenPlaced = true
	#When enabled, the mob spawners spawns are also disabled when a campfire is within the radius.
	preventMobSpawnerSpawns = false
	#By default set to 0.5. This means that if the radius is 16, the campfire burns prior mobs in a radius of 8.
	#Range: 0.0 ~ 1.0
	burnHostilesRadiusModifier = 0.5
	#The radius around the campfire in blocks where hostile mob spawns will be blocked.
	#Range: 1 ~ 128
	preventHostilesRadius = 48
	#When enabled, the mod will work with soul campfires.
	enableEffectForSoulCampfires = true
	#When enabled, the campfire only has an effect when the block is signalling.
	campfireMustBeSignalling = false
	#When enabled, the mod will work with normal campfires.
	enableEffectForNormalCampfires = true
	#When enabled, the campfire only has an effect when the block is lit up.
	campfireMustBeLit = true

