
[General]
	#When enabled, the shield will be hidden unless a player presses right-click.
	hideShieldWhenNotInUse = true
	#The percentage of damage that will be negated when a player is hit while holding a shield that's not held high.
	#Range: 0.0 ~ 1.0
	passiveShieldPercentageDamageNegated = 0.3333

