
[General]
	#When enabled, bees die after stinging a player. This takes roughly a few minutes.
	beesDieFromStingingPlayer = true
	#After a bee stings a player and its stinger is left behind, send the player a message.
	sendStungPlayerWithStingerAMessage = true
	#In order to make bees a little more common. Whenever a bee naturally spawns, the mod spawns an additional 'extraBeeSpawnsPerBee' bees.
	#Range: 0 ~ 50
	extraBeeSpawnsPerBee = 4
	#After a bee stings, it has a chance to leave its stinger inside the entity. It must be pulled out.
	beesLeaveTheirStinger = true
	#The chance the bee's stinger is pulled out by a player after right-clicking shears.
	#Range: 0.0 ~ 1.0
	chanceBeeStingerIsPulledOut = 0.5
	#The time in a seconds after a bee without its stinger dies.
	#Range: 0 ~ 600
	timeInSecondsBeeWithoutStingerDies = 60
	#The time in seconds a stinger that's left in an entity continues to pump poison.
	#Range: 0 ~ 300
	timeInSecondsStingerPumpsPoison = 30
	#The chance the bee's stinger lodges in the stung entity, resulting in death.
	#Range: 0.0 ~ 1.0
	chanceBeeLeavesItsStinger = 0.33
	#When enabled, bees die after stinging a mob. This takes roughly a few minutes.
	beesDieFromStingingMob = true

