
[General]
	#When enabled, Riptide can only be used without rain when the user is holding a bucket of water.
	mustHoldBucketOfWater = true
	#The riptide power of the trident is multiplied by this number on use. Allows traveling a greater distance with a single charge.
	#Range: 0.0 ~ 100.0
	tridentUsePowerModifier = 3.0
	#The amount of time a player needs to charge the trident before being able to use Riptide. Minecraft's default is 10.
	#Range: 0 ~ 20
	tridentUseDuration = 5

