
[General]
	#If enabled, shows the location of the villager in the death message.
	showLocation = true
	#If enabled, also shows death messages of modded villagers. If you've found a 'villager'-entity that isn't named let me know by opening an issue so I can add it in.
	mentionModdedVillagers = true

